"""A plan and A audit metadata must be separate product artifacts."""
from pathlib import Path

import app
from schemas.proposal_schema import BusinessProposal
from test_product_reliability_v3 import english_a_narrative
from workflow.product_output_policy import validate_english_document


def fixture():
    proposal = BusinessProposal.model_validate(english_a_narrative())
    proposal.product_acceptance = {
        'policy':'product-per-agent-one-correction-v1',
        'corrections_allowed_per_agent':1,
        'corrections':{'A':1},
        'correction_events':[{'stage':'A','reason':'Synthetic correction.'}],
        'unresolved_issues':[{'stage':'A_export','message':'Synthetic unresolved audit issue.'}],
        'status':'accepted_with_issues',
    }
    return proposal


def test_a_plan_excludes_audit_status_errors_and_generator_footer():
    proposal=fixture()
    plan=app.proposal_to_markdown(proposal)
    audit=app.proposal_audit_to_markdown(proposal)
    assert 'Formal Output and Unresolved Issues' not in plan
    assert 'accepted_with_issues' not in plan
    assert 'Synthetic unresolved audit issue' not in plan
    assert 'Generated by Open Proposal Agent' not in plan
    assert 'A Product Audit Report' in audit
    assert 'accepted_with_issues' in audit
    assert 'Synthetic unresolved audit issue' in audit
    assert 'Generated by Open Proposal Agent' in audit
    validate_english_document(plan)
    validate_english_document(audit)


def test_save_a_writes_clean_plan_and_separate_audit(tmp_path):
    proposal=fixture()
    plan_path=app.save_proposal_markdown(proposal,tmp_path)
    audit_path=app.proposal_audit_path(plan_path)
    assert plan_path.is_file() and audit_path.is_file()
    assert plan_path != audit_path
    plan=plan_path.read_text(encoding='utf-8')
    audit=audit_path.read_text(encoding='utf-8')
    assert '# A Product Audit Report' not in plan
    assert '# A Product Audit Report' in audit
    assert not list(tmp_path.glob('*_audit_audit.md'))
